CREATE TABLE friends (
  user_name VARCHAR(10) NOT NULL,
  friends_list JSONB NOT NULL,
  partition_nr INTEGER NOT NULL,
  PRIMARY KEY (user_name)
);
CREATE INDEX ON friends (partition_nr);

INSERT INTO friends(user_name, friends_list, partition_nr) VALUES
('user1', '{"fullName": "Relation 1", "changes": 1, "important": true, "businessValue": 300}', 1),
('user2', '{"fullName": "Relation 2", "changes": 1, "important": true, "businessValue": 320}', 2),
('user3', '{"fullName": "Relation 3", "changes": 1, "important": true, "businessValue": 100}', 3),
('user4', '{"fullName": "Relation 4", "changes": 1, "important": true, "businessValue": 150}', 1),
('user5', '{"fullName": "Relation 5", "changes": 1, "important": true, "businessValue": 110}', 1),
('user6', '{"fullName": "Relation 6", "changes": 1, "important": true, "businessValue": 10}', 2),
('user7', '{"fullName": "Relation 7", "changes": 1, "important": true, "businessValue": 3}', 3),
('user8', '{"fullName": "Relation 8", "changes": 1, "important": true, "businessValue": 10}', 4),
('user9', '{"fullName": "Relation 1", "changes": 1, "important": true, "businessValue": 300}', 1),
('user10', '{"fullName": "Relation 2", "changes": 1, "important": true, "businessValue": 320}', 2),
('user11', '{"fullName": "Relation 3", "changes": 1, "important": true, "businessValue": 100}', 3),
('user12', '{"fullName": "Relation 4", "changes": 1, "important": true, "businessValue": 150}', 1),
('user13', '{"fullName": "Relation 5", "changes": 1, "important": true, "businessValue": 110}', 1),
('user14', '{"fullName": "Relation 6", "changes": 1, "important": true, "businessValue": 10}', 2),
('user15', '{"fullName": "Relation 7", "changes": 1, "important": true, "businessValue": 3}', 3),
('user16', '{"fullName": "Relation 8", "changes": 1, "important": true, "businessValue": 10}', 4),
('user17', '{"fullName": "Relation 1", "changes": 1, "important": true, "businessValue": 300}', 1),
('user18', '{"fullName": "Relation 2", "changes": 1, "important": true, "businessValue": 320}', 2),
('user19', '{"fullName": "Relation 3", "changes": 1, "important": true, "businessValue": 100}', 3),
('user20', '{"fullName": "Relation 4", "changes": 1, "important": true, "businessValue": 150}', 1),
('user21', '{"fullName": "Relation 5", "changes": 1, "important": true, "businessValue": 110}', 1),
('user22', '{"fullName": "Relation 6", "changes": 1, "important": true, "businessValue": 10}', 2),
('user23', '{"fullName": "Relation 7", "changes": 1, "important": true, "businessValue": 3}', 3),
('user24', '{"fullName": "Relation 8", "changes": 1, "important": true, "businessValue": 10}', 4),
('user25', '{"fullName": "Relation 1", "changes": 1, "important": true, "businessValue": 300}', 1),
('user26', '{"fullName": "Relation 2", "changes": 1, "important": true, "businessValue": 320}', 2),
('user27', '{"fullName": "Relation 3", "changes": 1, "important": true, "businessValue": 100}', 3),
('user28', '{"fullName": "Relation 4", "changes": 1, "important": true, "businessValue": 150}', 1),
('user29', '{"fullName": "Relation 5", "changes": 1, "important": true, "businessValue": 110}', 1),
('user30', '{"fullName": "Relation 6", "changes": 1, "important": true, "businessValue": 10}', 2),
('user31', '{"fullName": "Relation 7", "changes": 1, "important": true, "businessValue": 3}', 3),
('user32', '{"fullName": "Relation 8", "changes": 1, "important": true, "businessValue": 10}', 4),
('user33', '{"fullName": "Relation 1", "changes": 1, "important": true, "businessValue": 300}', 1),
('user34', '{"fullName": "Relation 2", "changes": 1, "important": true, "businessValue": 320}', 2),
('user35', '{"fullName": "Relation 3", "changes": 1, "important": true, "businessValue": 100}', 3),
('user36', '{"fullName": "Relation 4", "changes": 1, "important": true, "businessValue": 150}', 1),
('user37', '{"fullName": "Relation 5", "changes": 1, "important": true, "businessValue": 110}', 1),
('user38', '{"fullName": "Relation 6", "changes": 1, "important": true, "businessValue": 10}', 2),
('user39', '{"fullName": "Relation 7", "changes": 1, "important": true, "businessValue": 3}', 3),
('user40', '{"fullName": "Relation 8", "changes": 1, "important": true, "businessValue": 10}', 4);
